name: Publish to WinGet
on: workflow_dispatch
#  release:
#    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: vim.vim.nightly
          installers-regex: 'gvim.*(x64|x86).exe$'
          token: ${{ secrets.WINGET_TOKEN }}
